spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1q2w3e4r
    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    encoding:
      charset: UTF-8
    converters:
      preferred-json-mapper: fastjson
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  redis:
  #集群模式
      #cluster:
      #  nodes:
      #    - 39.XXX.XX.69:6661
      #    - 39.XXX.XX.69:6662
      #    - 39.XXX.XX.69:6663
      #    - 39.XXX.XX.69:6664
      #    - 39.XXX.XX.69:6665
      #    - 39.XXX.XX.69:6666
      #单机模式
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000 #毫秒

##mybatis
mybatis:
  typeAliasesPackage: com.xiaomi.blog.domains
  mapper-locations: classath:mapper/*.xml


####服务端口配置
server:
  port: 8080


####日志配置
logging:
  file: blog.log
  path: logs/
  level.root: info



####add log config