spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1q2w3e4r
    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    encoding:
      charset: UTF-8
    converters:
      preferred-json-mapper: fastjson
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

####服务端口配置
server:
  port: 8080


####日志配置
logging:
  file: blog.log
  path: logs/
  level.root: info

####add log config